name: Maven publish
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
env:
  FROM_NOTIFICATION_EMAIL_ADDRESS: 'do-not-reply@example.com'
jobs:
  maven-push:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Maven
      uses: stCarolas/setup-maven@v3
      with:
        maven-version: 3.5.4
    - name: Run the Maven verify phase
      run: mvn -B verify --file pom.xml
    - name: Maven build
      run: mvn -s mvn-settings.xml -Dusername=${{ secrets.ARTIFACT_STORE_CLIENT_USERNAME }} -Dpassword=${{ secrets.ARTIFACT_STORE_CLIENT_PASSWORD }} compile
    - name: Maven test
      run: mvn -s mvn-settings.xml -Dusername=${{ secrets.ARTIFACT_STORE_CLIENT_USERNAME }} -Dpassword=${{ secrets.ARTIFACT_STORE_CLIENT_PASSWORD }} test
    - name: Maven generate Javadoc
      run: mvn -s mvn-settings.xml -Dusername=${{ secrets.ARTIFACT_STORE_CLIENT_USERNAME }} -Dpassword=${{ secrets.ARTIFACT_STORE_CLIENT_PASSWORD }} -DskipTests install javadoc:jar
    - name: Maven deploy
      run: |
        mvn -s mvn-settings.xml -Dusername=${{ secrets.ARTIFACT_STORE_CLIENT_USERNAME }} -Dpassword=${{ secrets.ARTIFACT_STORE_CLIENT_PASSWORD }} -DskipTests -DperformRelease deploy
    - name: Execute after step
      run: |
        [ -s "./pipeline-after.sh" ] && {
          chmod +x ./pipeline-after.sh
          ./pipeline-after.sh
        } || :
  notification:
    needs: [maven-push]
    runs-on: self-hosted
    if: failure()
    steps:
    - uses: actions/checkout@v2
    - name: Read teams channel from file
      id: teamschannel
      run: |
        [ -s "./.teamschannel" ] && {
          teams_channel=$(cat .teamschannel)
          echo "::set-output name=webhook-url::$teams_channel"
        } || :
    - name: Send message to ms teams
      if: steps.teamschannel.outputs.webhook-url != ''
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ steps.teamschannel.outputs.webhook-url }}
        title: Github Workflow Status
        summary: Maven Push failed for ${{ github.repository }}
        sections: '[{ "activityTitle": "Maven publish failed!",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "**Commit message**: ${{ github.event.head_commit.message}}, [click here to go the commit.](${{ github.event.head_commit.url }})"}]'
        actions: '[{ "@context": "http://schema.org", "@type": "OpenUri", "name": "Review Commit Diffs", "targets": [{ "os": "default", "uri": "${{ github.event.compare }}" }] }, { "@context": "http://schema.org", "@type": "OpenUri", "name": "Failed Build", "targets": [{ "os": "default", "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }] }]'
    - name: Check existence of file .watchers
      id: exists_watchers
      uses: andstor/file-existence-action@v1
      with:
        files: ".watchers"
    - name: Read watchers from file
      id: watchers
      run: |
        [ -s "./.watchers" ] && {
          watchers=$(cat .watchers)
          echo "::set-output name=email-ids::$watchers"
        } || :
    - name: Send a notification mail
      if: steps.watchers.outputs.email-ids != ''
      uses: wadeww/send-email-action@master
      with:
        server_address: ${{ secrets.SMTP_SERVER_ADDRESS }}
        port: 25
        subject: Github Workflow failed
        body: |
          Hello,

          The Github workflow publishing maven artifacts failed!

          Repository: https://github.com/${{ github.repository }}
          Commit Message: ${{ github.event.head_commit.message }}
          Commit Link: ${{ github.event.head_commit.url }}
          Failed Build: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Regards,
          2Tier Deployment Team
        to: ${{ steps.watchers.outputs.email-ids }}
        from: ${{ env.FROM_NOTIFICATION_EMAIL_ADDRESS }}
